# Generated by Django 5.0.6 on 2024-06-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_sector', models.IntegerField()),
                ('co2_revenues', models.FloatField()),
                ('water_revenues', models.FloatField()),
                ('energy_revenues', models.FloatField()),
                ('health_policy', models.BooleanField()),
                ('supply_chain_policy', models.BooleanField()),
                ('diversity_policy', models.BooleanField()),
                ('salary_gap', models.FloatField()),
                ('net_employement_creation', models.FloatField()),
                ('board_independency_policy', models.BooleanField()),
                ('board_diversity_policy', models.BooleanField()),
                ('board_experience_policy', models.BooleanField()),
                ('renewable_energy', models.FloatField()),
                ('market_gap', models.FloatField()),
                ('green_capex', models.BooleanField()),
            ],
        ),
    ]
