# Generated by Django 5.0.6 on 2024-06-30 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='net_employement_creation',
            new_name='net_employment_creation',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='codigo_sector',
            new_name='sector_code',
        ),
        migrations.AddField(
            model_name='empresa',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
