# Generated by Django 5.0.6 on 2024-06-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_rename_nombre_empresa_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='esg_score',
            field=models.FloatField(null=True),
        ),
    ]
